---
title: "Cluster_Cocacola & Dr Pepper"
author: "Stephanie Yang jy2777"
date: "12/2/2017"
output:
  pdf_document: default
  html_document: default
---

Coca Cola #4 Special
```{r}
setwd("~/Desktop/Homework/Statistical Methods/Project/datasets")
#transpose t()
cocacola.metrics <- t(read.csv("cocacola_metrics2.csv", header=FALSE))

#labels columns 
colnames(cocacola.metrics)<- c("Date","Likes (Total) FB","Comments (Total) FB","Shares (Total) FB","Reactions Per Post FB","Impressions (Total) FB","Impressions-viral (Total) FB","Impressions per Action FB","Impressions per Post FB","Actions (Total) FB","Actions per Impression (%) FB","Fans FB","Page Score FB","Posts (Total) FB","Average Engagement Per Post (%) FB","Actions Per Engager FB","Actions Per Post FB","Unique Engaged Audience FB","Average Click Engagement Per Post (%) FB","% Engaged Audience FB","% New Engagers FB","Posts (Category Total) FB","Clicks (Total) FB","Native Video Views (Lifetime Total) FB","Video (Total Actions) FB","% Shares FB","% Comments FB","% Likes FB","Likes (Total) TW","Retweets (Total) TW","Total Actions (% Followers) TW","Actions (Total) TW","Average Engagement Per Tweet (%) TW","Followers TW","Tweets (Total) TW","Clicks (Total) TW","Retweeter Followers (Average) TW","% Retweets TW","% Likes TW","Actions Per Tweet TW","Unique Engaged Audience TW","Unique Retweeters TW","% Engaged Audience TW","% New Engagers TW","Reactions (Total) FB","Actions Per Engager TW","Followers IG","Likes (Total) IG","Comments (Total) IG","Actions (Total) IG","Media (Total) IG","Average Engagement Per Media (%) IG","Actions Per Media IG","Photo (Total) IG","Video (Total) IG","Actions Per Engager IG","Unique Engaged Audience IG","Likes Per Media IG","% Likes IG","% Engaged Audience IG","% New Engagers IG","Videos (Total) YT","Likes (Total) YT","Dislikes (Total) YT","Comments (Total) YT","Views (Total) YT","Actions (Total) YT","Subscribers YT","Average Engagement Per Video (%) YT","Actions Per Video YT","% Likes YT","% Comments YT","% Views YT")

#removes duplicate row
cocacola.metrics1 <- cocacola.metrics[-1,]

##Cleaning the metrics sheet
#1) removes space in column titles
colnames(cocacola.metrics1) <- gsub(" ","",colnames(cocacola.metrics1))

#2) removes % symbol of column 10
cocacola.metrics1[,c(11,15,19,20,21,26,27,28,31,33,38,39,43,44,52,59,60,61,69,71,72,73)] <- as.numeric(gsub("%", "",cocacola.metrics1[,c(11,15,19,20,21,26,27,28,31,33,38,39,43,44,52,59,60,61,69,71,72,73)]))/100
cocacola.metrics1 <- as.data.frame(cocacola.metrics1)
class(cocacola.metrics1)

#3) removes comma separator for thousands, except for date column which is type character not numeric
#gsub to replace "," with "", and then convert the string to numeric using as.numeric
cocacola.metrics1[,2:73] <- lapply(cocacola.metrics1[,2:73], function(x) as.numeric(gsub(",","", as.character(x))))

##Transforms Monthly to Quarterly Data:
library("lubridate")  

#creates a year and quarter column per row
cocacola.metrics1$Date <- ymd(cocacola.metrics1$Date)
cocacola.metrics1$year = year(cocacola.metrics1$Date)
cocacola.metrics1$quarter = quarter(cocacola.metrics1$Date)

#aggregates quarters of same year and takes their sum (sales are aldo sums) : HOW TO DO IT WITH AGGREGATE()?
library("reshape2")
cocacola.metrics2 <- melt(cocacola.metrics1[,2:75], id=c("quarter", "year"))
cocacola.metrics2 <- dcast(cocacola.metrics2, year + quarter ~ variable, fun.aggregate = sum)
write.csv(cocacola.metrics2,file="cocacola_vizmetrics.csv")

d <- dist(cocacola.metrics2, method = "euclidean") # distance matrix
fit <- hclust(d, method="ward") 
plot(fit) # display dendogram
groups <- cutree(fit, k=3) # cut tree into 3 clusters
# draw dendogram with red borders around the 3 clusters 
rect.hclust(fit, k=3, border="red")
```


Dr. Pepper
```{r}
setwd("~/Desktop/Homework/Statistical Methods/Project/datasets")
#transpose t()
drpepper.metrics <- t(read.csv("drpepper_metrics2.csv", header=FALSE))

#labels columns 
colnames(drpepper.metrics)<- c("Date","Likes (Total) FB","Comments (Total) FB","Shares (Total) FB","Reactions Per Post FB","Impressions (Total) FB","Impressions-viral (Total) FB","Impressions per Action FB","Impressions per Post FB","Actions (Total) FB","Actions per Impression (%) FB","Fans FB","Page Score FB","Posts (Total) FB","Average Engagement Per Post (%) FB","Actions Per Engager FB","Actions Per Post FB","Unique Engaged Audience FB","Average Click Engagement Per Post (%) FB","% Engaged Audience FB","% New Engagers FB","Posts (Category Total) FB","Clicks (Total) FB","Native Video Views (Lifetime Total) FB","Video (Total Actions) FB","% Shares FB","% Comments FB","% Likes FB","Likes (Total) TW","Retweets (Total) TW","Total Actions (% Followers) TW","Actions (Total) TW","Average Engagement Per Tweet (%) TW","Followers TW","Tweets (Total) TW","Clicks (Total) TW","Retweeter Followers (Average) TW","% Retweets TW","% Likes TW","Actions Per Tweet TW","Unique Engaged Audience TW","Unique Retweeters TW","% Engaged Audience TW","% New Engagers TW","Reactions (Total) FB","Actions Per Engager TW","Followers IG","Likes (Total) IG","Comments (Total) IG","Actions (Total) IG","Media (Total) IG","Average Engagement Per Media (%) IG","Actions Per Media IG","Photo (Total) IG","Video (Total) IG","Actions Per Engager IG","Unique Engaged Audience IG","Likes Per Media IG","% Likes IG","% Engaged Audience IG","% New Engagers IG","Videos (Total) YT","Likes (Total) YT","Dislikes (Total) YT","Comments (Total) YT","Views (Total) YT","Actions (Total) YT","Subscribers YT","Average Engagement Per Video (%) YT","Actions Per Video YT","% Likes YT","% Comments YT","% Views YT")

#removes duplicate row
drpepper.metrics1 <- drpepper.metrics[-1,]

##Cleaning the metrics sheet
#1) removes space in column titles
colnames(drpepper.metrics1) <- gsub(" ","",colnames(drpepper.metrics1))

#2) removes % symbol of column 10
drpepper.metrics1[,c(11,15,19,20,21,26,27,28,31,33,38,39,43,44,52,59,60,61,69,71,72,73)] <- as.numeric(gsub("%", "",drpepper.metrics1[,c(11,15,19,20,21,26,27,28,31,33,38,39,43,44,52,59,60,61,69,71,72,73)]))/100
drpepper.metrics1 <- as.data.frame(drpepper.metrics1)
class(drpepper.metrics1)

#3) removes comma separator for thousands, except for date column which is type character not numeric
#gsub to replace "," with "", and then convert the string to numeric using as.numeric
drpepper.metrics1[,2:73] <- lapply(drpepper.metrics1[,2:73], function(x) as.numeric(gsub(",","", as.character(x))))

##Transforms Monthly to Quarterly Data:
library("lubridate")  

#creates a year and quarter column per row
drpepper.metrics1$Date <- ymd(drpepper.metrics1$Date)
drpepper.metrics1$year = year(drpepper.metrics1$Date)
drpepper.metrics1$quarter = quarter(drpepper.metrics1$Date)

#aggregates quarters of same year and takes their sum (sales are aldo sums) : HOW TO DO IT WITH AGGREGATE()?
library("reshape2")
drpepper.metrics2 <- melt(drpepper.metrics1[,2:75], id=c("quarter", "year"))
drpepper.metrics2 <- dcast(drpepper.metrics2, year + quarter ~ variable, fun.aggregate = sum)
write.csv(drpepper.metrics2,file="cocacola_vizmetrics.csv")

d <- dist(drpepper.metrics2, method = "euclidean") # distance matrix
fit <- hclust(d, method="ward") 
plot(fit) # display dendogram
groups <- cutree(fit, k=3) # cut tree into 3 clusters
# draw dendogram with red borders around the 3 clusters 
rect.hclust(fit, k=3, border="red")


```

